# Generated by Django 5.2.7 on 2025-10-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='pais',
            field=models.CharField(choices=[('CL', 'Chile'), ('AR', 'Argentina'), ('PE', 'Perú'), ('BR', 'Brasil'), ('US', 'Estados Unidos')], default='CL', max_length=2),
        ),
    ]
