# Generated by Django 5.2.7 on 2025-10-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0002_contacto_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='pais',
            field=models.CharField(choices=[('CL', 'Chile (+56)'), ('AR', 'Argentina (+54)'), ('PE', 'Perú (+51)'), ('BR', 'Brasil (+55)'), ('US', 'Estados Unidos (+1)'), ('MX', 'México (+52)'), ('CO', 'Colombia (+57)'), ('ES', 'España (+34)')], default='CL', max_length=2),
        ),
    ]
